"""empty message

Revision ID: 630abc3b01cb
Revises: 2807edd385a2
Create Date: 2021-12-01 17:59:47.164115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630abc3b01cb'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('company', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('job_title', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('slogan', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('youtube', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('linkedin', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('tiktok', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('behance', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('snapchat', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('maps', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('sector', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'sector')
    op.drop_column('user', 'website')
    op.drop_column('user', 'maps')
    op.drop_column('user', 'snapchat')
    op.drop_column('user', 'behance')
    op.drop_column('user', 'tiktok')
    op.drop_column('user', 'linkedin')
    op.drop_column('user', 'youtube')
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'description')
    op.drop_column('user', 'slogan')
    op.drop_column('user', 'job_title')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'company')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
